### PR TITLE
Use moment.js library for date functions, locales and timezones

### PR DESCRIPTION
**Pull request by jazdw**
Something to consider, perhaps for a new version of the datetimepicker.

### CODE REVIEW

**Comment by Reltik** [comment]
I think this is an excellent idea.

**Comment by solhuebner** [comment]
Nice

**Comment by rsurjano** [comment]
nice idea! plz in future versions dont use function eval() :(

**Comment by jazdw** [comment]
@rsurjano I didn't?

**Comment by rsurjano** [comment]
In this line you use eval() :(
https://github.com/xdan/datetimepicker/blob/master/jquery.datetimepicker.js#L2017

**Comment by jazdw** [comment]
@rsurjano I think you may need to go back and take another look, my pull request actually removes that line. Its also not a part of the datetimepicker project, they inlined another library for the Date functions.

**Comment by Zalmoxisus** [comment]
@jazdw, thanks a lot! Great pull request, and, as I see, a lot of people want to use Momentjs instead of Baron Schwartz's library, but I guess it will never be merged as it will break back compatibility. So I forked/ported the Datetimepicker, adopted it to Momentjs according to this pull request, added last updates, fixed conflicts and other issues: https://github.com/Zalmoxisus/momentjs-datetimepicker

**Comment by desfero** [comment]
Thanks, we should consider to add link to momentjs-datetimepicker to documentation

**Pull request closed without merging**
