### PR TITLE
add feature allow date by regex

### PR DESCRIPTION
**Pull request by xiaoyu5256**
I want allow to choose some day by dynamic,for example choose the last day of quarter every year,so I  add this feature.

### CODE REVIEW

**Comment by 1allen** [comment]
any docs/examples available for this feature?

**Comment by xiaoyu5256** [comment]
@xdan How to `allowDateRe` and `allowDate` add docs
{format:'Y-m-d',allowDateRe:'\\d{4}-(03-31|06-30|09-30|12-31)' }

@1allen

**Comment by xdan** [comment]
Hey. Added doc.tpl file in the repository . From this information goes directly to the documentation on the website .

**Comment by xiaoyu5256** [comment]
@1allen  #391

**Pull request merged**
