### PR TITLE
Highlight dates and periods

### PR DESCRIPTION
**Pull request by Mingpao**
Added options to highlight individual dates or periods with color and text notes.

Format for individual dates: `"<date>(,<text note>)(,<css element>)"`
Format for periods: `"<start date>,<end date>(,<text note>)(,<css element>)"`

Example: 
```javascript
jQuery('#datetimepicker').datetimepicker({
 formatDate: "d.m.Y", 
 highlightedDates: [
	"29.04.2015,Meeting with Pete", 
	"24.12.2015,Christmas Eve,xdsoft_highlighted_mint", 
	"25.12.2015,Christmas Day,xdsoft_highlighted_mint", 
	"26.11.2015,Thanksgiving"
 ],
 highlightedPeriods: [
	"27.04.2015,08.05.2015,Business trip", 
	"11.07.2015,31.08.2015,Summer holiday 2015,xdsoft_highlighted_mint", 
	"21.12.2015,01.01.2016,Christmas holiday 2015"
 ]
});
```

ScreenShot

ScreenShot

ScreenShot

### CODE REVIEW

**Comment by benaref** [comment]
How to get the day's title onSelectDate?

**Comment by Drasius2** [comment]
Live working demo: [https://plnkr.co/edit/Q5m9rPlZO2SKhKTRErUQ](url)

**Comment by Drasius2** [comment]
Hello. I
 am trying to change highlighted days after datetimepicker is initiated, but the highlighted days are not updated on next "onShow" event. Is it posible to update date time picker without destroying and reinicializing it? Check this plunker example: [https://plnkr.co/edit/4HkCp5](https://plnkr.co/edit/4HkCp5)

**Comment by DMWOO7** [comment]
Awesome feature! Thanks for this 👍  
But it should be added in the [documentation](http://xdsoft.net/jqplugins/datetimepicker/) too. I found it by searching cause I saw the demo screens here on github, want to use this function and couldn't find anything in the docs about it.

**Pull request merged**
