### PR TITLE
Bug with 12 hour time format

### PR DESCRIPTION
**Pull request by Thomo87**
If you use datetimepicker with the following conditions:

formatTime:'g:i A', format: 'd/m/Y h:i A'

Then when you select either of the 12 hour options, either 12PM or 12AM, the meridiem is flipped.

After some testing I narrowed it down to the changes proposed.

Thanks.

### CODE REVIEW

**Comment by Thomo87** [comment]
After submitting this change I noticed the previous pull request fixes the same issue with a different approach, pull #476

**Comment by nfauchelle** [comment]
I would like to be able to compare them, but it looks like you only changed jquery.datetimepicker.full.min.js, which makes it very hard to see a diff.

**Comment by Thomo87** [comment]
From my understanding, both are required depending on which version is being used.

**Comment by nfauchelle** [comment]
@Thomo87 
What I mean is from what I can tell your changes were done in jquery.datetimepicker.full.min.js which is minified and very hard to diff.

I think you also need to make your change against jquery.datetimepicker.full.js - so people can see what changed.

**Comment by jaythomas** [comment]
@Thomo87, modifying the full.min.js won't help. The problem needs to be fixed in the source code, which generates the full.min.js file.

**Comment by xdan** [comment]
Please fix only jquery.datetimepicker.js file

**Pull request closed without merging**
