### PR TITLE
Fix dayOfWeek for Indonesian language

### PR DESCRIPTION
**Pull request by arsya**
Fix Indonesian dayOfWeek which previously starts with Monday instead of Sunday. Now it starts with Sunday.

### CODE REVIEW

**Comment by xdan** [comment]
All languages start with Sunday. you can change this with dayOfWeekStart options
default = 0, but you can use dayOfWeekStart:6 and your week will start from Monday

**Comment by arsya** [comment]
@xdan, thanks for letting me know about the dayOfWeekStart option. I just think that since all languages start with Sunday, I made a change to the code to make it the same. Hopefully, you could merge it.
Thanks for such an awesome plugin.

**Comment by xdan** [comment]
Oooo, sorry) I thought that Min is monday) Sorry)

**Comment by arsya** [comment]
No problem. Thanks for merging.

**Pull request merged**
