### PR TITLE
added default minDateTime

### PR DESCRIPTION
**Pull request by obxpete**
@u01jmg3 requested a default value for minDateTime here:   e7f38dc52af22fdd6a06fbee5779b6f61d66a4bf

**consider** putting this option in documentation on http://xdsoft.net/jqplugins/datetimepicker/. :+1:

### CODE REVIEW

**Comment by u01jmg3** [comment]
:+1:

**Comment by 1allen** [comment]
:+1:

**Comment by xdan** [comment]
Hi, added in 2.5.9. thank you
Could not take your pull

**Comment by xdan** [comment]
I added the code myself, because I could not do it automatically. Thanks for your pull request. Can i close it?

**Comment by obxpete** [comment]
yes. thank you.

Pete Lombardo
obxpete@gmail.com
uncoditional.com
@obxpete

**Pull request closed without merging**
